### ISSUE TITLE
Dll missing?

### ISSUE THREAD

**Issue by shuksieno123** [dnkaUC/ayywareRemake#3]
Where is the dll did i have to compile it myself or is there somewhere the dll ?

**Comment by dnkaUC** [comment]
I will add the DLL later for now you have to compile it by urself.

**Comment by JarrettFritz** [comment]
what injector do you use? Or do you have your own coded one?

**Comment by schulzjona** [comment]
Just launch your game with -INSECURE and then use the ExtremeInjector. Easy to use.

**Comment by JarrettFritz** [comment]
and then it still can play online? Insecure makes it so you cant normally play on vac servers. Also, how do you open the menu?

**Comment by schulzjona** [comment]
Press "Insert" on your keyboard.
You can play on hvh Server then, but not on official ds from volvo
